declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  type IconProps = SVGProps<SVGSVGElement> & {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  };

  export const ChevronDown: FC<IconProps>;
  export const AlertTriangle: FC<IconProps>;
  export const AlertCircle: FC<IconProps>;
  export const Info: FC<IconProps>;
  export const CheckCircle: FC<IconProps>;
  export const Wrench: FC<IconProps>;
  export const Search: FC<IconProps>;
  export const Plus: FC<IconProps>;
  export const Edit2: FC<IconProps>;
  export const Trash2: FC<IconProps>;
  export const Eye: FC<IconProps>;
  export const Save: FC<IconProps>;
  export const X: FC<IconProps>;
  export const ArrowLeft: FC<IconProps>;
  export const Bot: FC<IconProps>;
  export const Send: FC<IconProps>;
  export const Sparkles: FC<IconProps>;
  export const ShieldCheck: FC<IconProps>;
  export const Cookie: FC<IconProps>;
  export const SlidersHorizontal: FC<IconProps>;
  export const Check: FC<IconProps>;
  export const Menu: FC<IconProps>;
  export const Globe: FC<IconProps>;
  export const Code2: FC<IconProps>;
  export const Smartphone: FC<IconProps>;
  export const Database: FC<IconProps>;
  export const Layout: FC<IconProps>;
  export const Blocks: FC<IconProps>;
  export const Brain: FC<IconProps>;
  export const Cloud: FC<IconProps>;
  export const Megaphone: FC<IconProps>;
  export const Palette: FC<IconProps>;
  export const Briefcase: FC<IconProps>;
  export const Zap: FC<IconProps>;
  export const Moon: FC<IconProps>;
  export const Sun: FC<IconProps>;
  export const Monitor: FC<IconProps>;
  export const Calendar: FC<IconProps>;
  export const User: FC<IconProps>;
  export const ArrowRight: FC<IconProps>;
  export const BookOpen: FC<IconProps>;
  export const TrendingUp: FC<IconProps>;
  export const Mail: FC<IconProps>;
  export const Phone: FC<IconProps>;
  export const MessageCircle: FC<IconProps>;
  export const Clock: FC<IconProps>;
  export const MapPin: FC<IconProps>;
  export const Quote: FC<IconProps>;
  export const CheckCircle2: FC<IconProps>;
  export const ExternalLink: FC<IconProps>;
  export const Shield: FC<IconProps>;
  export const BarChart3: FC<IconProps>;
  export const Package: FC<IconProps>;
  export const ShoppingBag: FC<IconProps>;
  export const Terminal: FC<IconProps>;
  export const Cpu: FC<IconProps>;
  export const Settings: FC<IconProps>;
  export const Circle: FC<IconProps>;
  export const Globe2: FC<IconProps>;
  export const MonitorSmartphone: FC<IconProps>;
  export const Rocket: FC<IconProps>;
  export const Users: FC<IconProps>;
  export const Wand2: FC<IconProps>;
}
